# Generated by Django 5.2.15 on 2026-06-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("call_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("store", models.CharField(blank=True, max_length=32)),
                ("caller_phone_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("faq_answered", "FAQ answered"),
                            ("suggested", "Suggested"),
                            ("escalation", "Escalation"),
                            ("vendor_callback", "Vendor callback"),
                            ("abandoned", "Abandoned"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("escalated", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("duration_s", models.IntegerField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("assistant_id", models.CharField(blank=True, max_length=64)),
                ("suggested_skus", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VapiObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant"),
                            ("squad", "Squad"),
                            ("tool", "Tool"),
                            ("phone_number", "Phone number"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("vapi_id", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "name"],
                "unique_together": {("kind", "name")},
            },
        ),
        migrations.CreateModel(
            name="VoiceTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.IntegerField()),
                ("role", models.CharField(max_length=16)),
                ("text", models.TextField(blank=True)),
                ("tool_name", models.CharField(blank=True, max_length=64)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="voice.voicecall",
                    ),
                ),
            ],
            options={
                "ordering": ["call", "seq"],
                "unique_together": {("call", "seq")},
            },
        ),
    ]
