# Generated by Django 5.2.15 on 2026-06-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vapiobject",
            name="last_provision_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="vapiobject",
            name="kind",
            field=models.CharField(
                choices=[
                    ("assistant", "Assistant"),
                    ("squad", "Squad"),
                    ("tool", "Tool"),
                    ("phone_number", "Phone number"),
                    ("file", "File"),
                ],
                max_length=16,
            ),
        ),
    ]
