# Generated by Django 5.2.15 on 2026-06-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0002_vapiobject_last_provision_hash_alter_vapiobject_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicecall",
            name="human_requested_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="voicecall",
            name="transfer_disposition",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="voicecall",
            name="transfer_number_key",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
