# Generated by Django 5.2.15 on 2026-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_voicecall_human_requested_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('tool_call_id', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=64)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('store', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='webhook', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('call_id', 'tool_call_id', 'name')},
            },
        ),
    ]
