# Generated by Django 5.2.17 on 2026-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0005_alter_voicecall_outcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicecall",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("faq_answered", "FAQ answered"),
                    ("suggested", "Suggested"),
                    ("escalation", "Escalation"),
                    ("vendor_callback", "Vendor callback"),
                    ("vendor_direct", "Vendor sent to owner"),
                    ("transfer_unavailable", "Transfer: person unavailable"),
                    ("abandoned", "Abandoned"),
                    ("error", "Error"),
                ],
                max_length=32,
            ),
        ),
    ]
