# Generated by Django 5.2.15 on 2026-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RankingWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("w_anon", models.JSONField(default=dict)),
                ("w_known", models.JSONField(default=dict)),
                ("margin_emphasis", models.FloatField(default=1.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Ranking weights",
            },
        ),
    ]
