# Generated by Django 5.2.17 on 2026-10-02 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_botcapability'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('beat', 'beat'), ('cron', 'cron'), ('manual', 'manual')], max_length=8)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
