# Generated by Django 5.2.17 on 2026-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_jobrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorAllowlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=16, unique=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "store",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any store"),
                            ("yakima", "Yakima"),
                            ("mount-vernon", "Mount Vernon"),
                            ("pullman", "Pullman"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
                ("match_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
