"""voice/pricing.py OTD uplift — deterministic per-store, monotonic, guarded (21-SPEC E1/E2).

Expected values are HAND-AUTHORED (not generated by the code under test). Offline, no network.
"""

from voice import pricing


def test_spoken_price_is_tts_friendly():
    """The agent voices price_spoken, never the digits — so '$16.34' can't be read 'dollar 16.34'."""
    assert pricing.spoken(16.34) == "16 dollars and 34 cents"
    assert pricing.spoken(30) == "30 dollars"
    assert pricing.spoken(30.0) == "30 dollars"
    assert pricing.spoken(1) == "1 dollar"  # singular
    assert pricing.spoken(1.05) == "1 dollar and 5 cents"
    assert pricing.spoken(0.5) == "50 cents"  # cents-only
    assert pricing.spoken(16.999) == "17 dollars"  # rounding carry, no "100 cents"
    assert pricing.spoken(0) == ""  # non-positive → say nothing (Numbers-Guard)
    assert pricing.spoken(None) == ""
    assert pricing.spoken("nope") == ""


def test_otd_multiplier_per_store_handauthored():
    # Yakima: (1 + 0.37) * (1 + 0.084) = 1.37 * 1.084 = 1.48508
    assert pricing.otd_multiplier("yakima") == 1.48508
    # Mt Vernon: 1.37 * 1.088 = 1.49056
    assert pricing.otd_multiplier("mount-vernon") == 1.49056
    # Pullman: 1.37 * 1.089 = 1.49193
    assert pricing.otd_multiplier("pullman") == 1.49193
    # Unknown / combined → excise only (no local) → 1.37
    assert pricing.otd_multiplier("combined") == 1.37
    assert pricing.otd_multiplier(None) == 1.37


def test_otd_value_per_store():
    # 38.00 pre-tax in Yakima → 38 * 1.48508 = 56.43 (rounded to cents)
    assert pricing.otd(38.0, "yakima") == 56.43
    # 38.00 unknown store → 38 * 1.37 = 52.06
    assert pricing.otd(38.0, "combined") == 52.06


def test_otd_is_monotonic_ge_price():
    for p in (1.0, 12.5, 38.0, 200.0):
        assert pricing.otd(p, "yakima") >= p
        assert pricing.otd(p, "pullman") >= p


def test_otd_guards_zero_negative_and_junk():
    assert pricing.otd(0, "yakima") == 0.0
    assert pricing.otd(-5, "yakima") == 0.0
    assert pricing.otd(None, "yakima") == 0.0
    assert pricing.otd("not-a-number", "yakima") == 0.0
