"""P2 — deterministic outcome classification (12-P2 §4.4 / AC C1-C3).

Hand-authored fixture table; expected values are NOT generated by the code under test. No network,
no DB (pure functions over dicts). Precedence: defective > repeated_request > dispute > vendor >
suggested > faq > abandoned.
"""

from __future__ import annotations

from voice import outcomes
from voice.models import Outcome


def _eocr(transcript="", *, structured=None, ended="customer-ended-call", messages=None, **extra):
    msg = {
        "type": "end-of-call-report",
        "transcript": transcript,
        "endedReason": ended,
        "messages": messages or [],
    }
    if structured is not None:
        msg["analysis"] = {"structuredData": structured}
    msg.update(extra)
    return msg


# ── C1: >=2 human requests → escalation / repeated_request / immediate ─────────


def test_two_human_requests_escalates_repeated():
    m = _eocr("Can I talk to a person? ... No, I really want to speak with a human.")
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.ESCALATION
    assert reason == outcomes.REASON_REPEATED
    assert outcomes.is_immediate_alert(outcome, reason) is True


def test_structured_human_requested_count_escalates():
    m = _eocr("blah", structured={"human_requested": 2})
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert (outcome, reason) == (Outcome.ESCALATION, outcomes.REASON_REPEATED)
    assert outcomes.human_requested_count(m, m["transcript"]) == 2


# ── C2: defective → defective_return / immediate; dispute → dispute / immediate ─


def test_defective_product_escalates_defective():
    m = _eocr("My vape cart is defective and won't fire, I want a refund.")
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.ESCALATION
    assert reason == outcomes.REASON_DEFECTIVE
    assert outcomes.is_immediate_alert(outcome, reason) is True


def test_return_dispute_no_defect_escalates_dispute():
    m = _eocr("You charged me for two but I only got one.")
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.ESCALATION
    assert reason == outcomes.REASON_DISPUTE
    assert outcomes.is_immediate_alert(outcome, reason) is True


def test_defective_beats_dispute_precedence():
    """A call that has BOTH a defect signal and a dispute signal → defective wins (highest sev)."""
    m = _eocr("My cart is broken AND you charged me twice, I want a refund.")
    _, reason = outcomes.classify_outcome(m, m["transcript"])
    assert reason == outcomes.REASON_DEFECTIVE


def test_structured_reason_overrides_lexicon():
    """The model-emitted structuredData.reason wins when it's a known escalation reason."""
    m = _eocr("generic talk", structured={"reason": "dispute"})
    _, reason = outcomes.classify_outcome(m, m["transcript"])
    assert reason == outcomes.REASON_DISPUTE


# ── C3: a SINGLE human request does NOT escalate (the "ask twice" gate) ────────


def test_single_human_request_does_not_escalate():
    m = _eocr("Can I talk to a person about your hours?")
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert outcome != Outcome.ESCALATION
    assert reason == ""
    assert outcomes.is_immediate_alert(outcome, reason) is False
    assert outcomes.human_requested_count(m, m["transcript"]) == 1


# ── softer outcomes (not immediate) ───────────────────────────────────────────


def test_suggestion_made_via_structured():
    m = _eocr("I'd like a relaxing edible", structured={"outcome": "suggested"})
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert (outcome, reason) == (Outcome.SUGGESTED, "")
    assert outcomes.is_immediate_alert(outcome, reason) is False


def test_suggestion_made_via_tool_turn():
    m = _eocr("recommend something", messages=[{"role": "tool", "name": "suggest_products"}])
    outcome, _ = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.SUGGESTED


def test_plain_faq_is_faq_answered():
    m = _eocr("What time do you close?")
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert (outcome, reason) == (Outcome.FAQ_ANSWERED, "")
    assert outcomes.is_immediate_alert(outcome, reason) is False


def test_empty_call_is_abandoned():
    m = _eocr("", messages=[])
    outcome, _ = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.ABANDONED


def test_error_ending_is_error():
    m = _eocr("partial", ended="pipeline-error-failed")
    outcome, _ = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.ERROR


def test_vendor_callback_label_is_immediate():
    m = _eocr("dropping off product", structured={"outcome": "vendor_callback"})
    outcome, reason = outcomes.classify_outcome(m, m["transcript"])
    assert outcome == Outcome.VENDOR_CALLBACK
    assert outcomes.is_immediate_alert(outcome, reason) is True


# ── transfer disposition inference (§4.3) ─────────────────────────────────────


def test_transfer_disposition_connected_on_destination():
    m = _eocr("transferring", destination={"type": "number", "number": "+1509"})
    transferred, disp = outcomes.transfer_disposition(m, outcomes.REASON_DEFECTIVE)
    assert transferred is True
    assert disp == "connected"


def test_transfer_disposition_no_answer():
    m = _eocr("transferring", ended="transfer-failed-no-answer")
    transferred, disp = outcomes.transfer_disposition(m, outcomes.REASON_REPEATED)
    assert transferred is True
    assert disp == "no_answer"


def test_transfer_disposition_not_attempted_when_no_escalation():
    m = _eocr("just a question")
    transferred, disp = outcomes.transfer_disposition(m, "")
    assert transferred is False
    assert disp == "not_attempted"
