# Generated by Django 5.2.15 on 2026-06-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("entry_router", "Entry router"),
                            ("budtender", "Budtender"),
                            ("faq", "FAQ"),
                            ("vendor", "Vendor"),
                            ("escalation", "Escalation"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("body", models.TextField()),
                ("vapi_model", models.CharField(blank=True, max_length=64)),
                ("voice_id", models.CharField(blank=True, max_length=64)),
                ("tool_names", models.JSONField(blank=True, default=list)),
                ("vapi_assistant_id", models.CharField(blank=True, max_length=64)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_output_tokens", models.IntegerField(blank=True, null=True)),
                ("prompt_version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("source_url", models.URLField(blank=True)),
                ("provisional", models.BooleanField(default=True)),
                ("weight", models.IntegerField(default=60)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="EducationDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=48)),
                ("body", models.TextField()),
                ("source_url", models.URLField(blank=True)),
                ("provisional", models.BooleanField(default=True)),
                ("weight", models.IntegerField(default=80)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["topic", "slug"],
            },
        ),
        migrations.CreateModel(
            name="FAQEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("paraphrases", models.JSONField(blank=True, default=list)),
                ("store", models.CharField(blank=True, max_length=32)),
                ("topic", models.CharField(blank=True, max_length=32)),
                ("weight", models.IntegerField(default=100)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-weight", "key"],
            },
        ),
        migrations.CreateModel(
            name="FlowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("graph", models.JSONField(default=dict, help_text="{nodes:[...], edges:[...]}")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("return_policy", "Return policy"),
                            ("privacy", "Privacy"),
                            ("loyalty", "Loyalty terms"),
                            ("other", "Other policy"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("citation", models.CharField(blank=True, max_length=64)),
                ("source_url", models.URLField(blank=True)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="policy/")),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("weight", models.IntegerField(default=120)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("store", models.CharField(blank=True, max_length=32)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("phone", "Phone"),
                            ("hours", "Hours"),
                            ("email", "Email"),
                            ("payment", "Payment"),
                            ("pickup", "Pickup"),
                            ("special", "Weekly special"),
                            ("limit", "WA purchase limit"),
                            ("age", "Age requirement"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("value", models.TextField(blank=True)),
                ("confirmed", models.BooleanField(default=True)),
                ("weight", models.IntegerField(default=110)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["store", "kind", "label"],
                "unique_together": {("store", "kind", "label")},
            },
        ),
        migrations.CreateModel(
            name="WeightTypeTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        choices=[
                            ("weight", "Flower/concentrate weight"),
                            ("cart_size", "Cartridge size"),
                            ("preroll", "Pre-roll format"),
                            ("edible_dose", "Edible dosing"),
                            ("concentrate_subtype", "Concentrate subtype"),
                            ("flower_form", "Flower form"),
                            ("strain_type", "Strain type"),
                            ("ratio", "THC:CBD ratio"),
                            ("limit", "WA purchase limit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("term", models.CharField(max_length=64)),
                ("value", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("weight", models.IntegerField(default=90)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Weight/type taxonomy",
                "ordering": ["axis", "id"],
                "unique_together": {("axis", "term")},
            },
        ),
    ]
