# Generated by Django 5.2.15 on 2026-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprompt",
            name="last_publish_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="last_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="transfer_number_key",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
