# Generated by Django 5.2.15 on 2026-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_agentprompt_last_publish_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='model_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='voice_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='voice_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
