# Generated by Django 5.2.15 on 2026-07-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_agentprompt_model_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('applied', 'Applied'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='running', max_length=16)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('publish_results', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='blogdoc',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogdoc',
            name='scrape_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogdoc',
            name='scrape_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='blogdoc',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='educationdoc',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdoc',
            name='scrape_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='educationdoc',
            name='scrape_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='educationdoc',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='scrape_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='scrape_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='scrape_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='scrape_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='storefact',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefact',
            name='scrape_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='storefact',
            name='scrape_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='storefact',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='storefact',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
