# Generated by Django 5.2.11 on 2026-09-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_policycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefact',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefact',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
