# Generated by Django 5.2.11 on 2026-09-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_storefact_valid_from_storefact_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='first_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentprompt',
            name='role',
            field=models.CharField(choices=[('entry_router', 'Entry router'), ('budtender', 'Budtender'), ('faq', 'FAQ'), ('vendor', 'Vendor'), ('escalation', 'Escalation'), ('written', 'Website chat (written)')], max_length=32, unique=True),
        ),
    ]
