# Generated by Django 5.2.17 on 2026-10-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_agentprompt_first_message_written_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprompt',
            name='transfer_number_key',
        ),
    ]
