# Generated by Django 5.2.17 on 2026-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0008_remove_agentprompt_transfer_number_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprompt",
            name="role",
            field=models.CharField(
                choices=[
                    ("entry_router", "Entry router"),
                    ("budtender", "Budtender"),
                    ("faq", "FAQ"),
                    ("vendor", "Vendor"),
                    ("escalation", "Escalation"),
                    ("written", "Website chat (written)"),
                    ("concierge", "Phone agent (all-in-one)"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
