# Generated by Django 5.2.15 on 2026-07-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutchieWriteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('acct_id', models.BigIntegerField(blank=True, null=True)),
                ('shipment_id', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('ok', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutchie_acct_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mjstateidno', models.CharField(blank=True, max_length=120)),
                ('over_21', models.BooleanField(null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('raw_scan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['dutchie_acct_id'], name='customers_c_dutchie_a77c1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=120)),
                ('budtender', models.CharField(blank=True, max_length=150)),
                ('acct_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('how_started', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('open', 'open'), ('checked_out', 'checked out'), ('abandoned', 'abandoned')], db_index=True, default='open', max_length=16)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('items_viewed', models.PositiveIntegerField(default=0)),
                ('items_added', models.PositiveIntegerField(default=0)),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_shipment_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['store', 'started_at'], name='customers_s_store_748b26_idx'), models.Index(fields=['budtender'], name='customers_s_budtend_c95737_idx'), models.Index(fields=['outcome'], name='customers_s_outcome_7697bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('budtender', models.CharField(blank=True, max_length=150)),
                ('acct_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=120)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.shopvisit')),
            ],
            options={
                'ordering': ['at'],
                'indexes': [models.Index(fields=['kind', 'at'], name='customers_s_kind_3dfca7_idx'), models.Index(fields=['at'], name='customers_s_at_6aee47_idx'), models.Index(fields=['kind', 'category'], name='customers_s_kind_01606f_idx'), models.Index(fields=['kind', 'brand'], name='customers_s_kind_20af27_idx')],
            },
        ),
    ]
