# Generated by Django 5.2.15 on 2026-07-07 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopvisit',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopvisit',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shopvisit',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('claimed', 'claimed')], db_index=True, default='claimed', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('budtender', 'budtender'), ('door', 'door'), ('admin', 'admin')], default='budtender', max_length=12)),
                ('store', models.CharField(blank=True, max_length=120)),
                ('register_id', models.CharField(blank=True, max_length=40)),
                ('register_name', models.CharField(blank=True, max_length=120)),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddField(
            model_name='dutchiewriteaudit',
            name='staff_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writes', to='customers.staffsession'),
        ),
        migrations.AddField(
            model_name='shopvisit',
            name='staff_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='customers.staffsession'),
        ),
        migrations.AddIndex(
            model_name='shopvisit',
            index=models.Index(fields=['store', 'status', 'ended_at'], name='customers_s_store_057e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsession',
            index=models.Index(fields=['username', 'login_at'], name='customers_s_usernam_f01ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsession',
            index=models.Index(fields=['store', 'login_at'], name='customers_s_store_257e44_idx'),
        ),
    ]
