# Generated by Django 5.2.15 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_shopvisit_claimed_at_shopvisit_claimed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="dutchie_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_expiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="customer",
            name="middle_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
