# Generated by Django 5.2.15 on 2026-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_full_id_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsession',
            name='dutchie_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='dutchie_permissions_known',
            field=models.BooleanField(default=False),
        ),
    ]
