# Generated by Django 5.2.15 on 2026-06-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        ("voice", "0003_voicecall_human_requested_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sink", models.CharField(max_length=24)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voice_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_deliveries",
                        to="voice.voicecall",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("voice_call", "sink")},
            },
        ),
    ]
