# Generated by Django 5.2.15 on 2026-06-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alertdelivery"),
        ("voice", "0003_voicecall_human_requested_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorCallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vapi_call_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("store", models.CharField(max_length=32)),
                ("reason", models.CharField(blank=True, max_length=32)),
                ("summary", models.TextField(blank=True)),
                ("caller_name", models.CharField(blank=True, max_length=128)),
                ("caller_phone_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("callback_window", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("alerted", models.BooleanField(default=False)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voice_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_callbacks",
                        to="voice.voicecall",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
