# Generated by Django 5.2.15 on 2026-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_vendorcallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('orders', models.IntegerField(default=0)),
                ('total_spend', models.FloatField(default=0.0)),
                ('aov', models.FloatField(default=0.0)),
                ('recency_days', models.IntegerField(blank=True, null=True)),
                ('cadence_days', models.IntegerField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, db_index=True, max_length=40)),
                ('persona', models.CharField(blank=True, max_length=80)),
                ('cohort_month', models.CharField(blank=True, max_length=16)),
                ('medical_share', models.FloatField(default=0.0)),
                ('is_medical', models.BooleanField(default=False)),
                ('top_brand', models.CharField(blank=True, max_length=120)),
                ('top_vendor', models.CharField(blank=True, max_length=120)),
                ('first_order', models.CharField(blank=True, max_length=32)),
                ('last_order', models.CharField(blank=True, max_length=32)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('tier_by_category', models.JSONField(blank=True, default=dict)),
                ('favorites', models.JSONField(blank=True, default=list)),
                ('favorite_brands', models.JSONField(blank=True, default=list)),
                ('hourly_pattern', models.JSONField(blank=True, default=list)),
                ('day_pattern', models.JSONField(blank=True, default=list)),
                ('store_affinity', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_spend', 'customer_key'],
                'indexes': [models.Index(fields=['-total_spend'], name='crm_custome_total_s_b761b7_idx'), models.Index(fields=['segment'], name='crm_custome_segment_ef3689_idx')],
            },
        ),
    ]
