# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="phone_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
