# Generated by Django 5.2.17 on 2026-10-09 01:33

from datetime import date

from django.db import migrations, models


# A migration is a frozen snapshot, so these helpers deliberately do not import crm.models; a test
# (test_customer_list_columns.py) pins them to ``CustomerProfile.sync_denormalised``.
def _label(entry, *keys):
    if isinstance(entry, dict):
        entry = next((entry[k] for k in keys if entry.get(k)), "")
    return str(entry).strip() if entry else ""


def _day(value):
    try:
        return date.fromisoformat(str(value or "").strip()[:10])
    except ValueError:
        return None


def backfill_list_columns(apps, schema_editor):
    CustomerProfile = apps.get_model("crm", "CustomerProfile")
    batch = []
    for p in CustomerProfile.objects.only(
        "id", "top_categories", "top_brand", "favorite_brands", "first_order", "last_order"
    ).iterator(chunk_size=1000):
        p.top_category = next(
            (n for e in p.top_categories or [] if (n := _label(e, "category", "Category"))), ""
        )[:80]
        names = dict.fromkeys(
            n
            for b in [p.top_brand, *(p.favorite_brands or [])]
            if (n := _label(b, "brand", "Brand", "name").lower().replace("|", " "))
        )
        p.brands_text = f"|{'|'.join(names)}|" if names else ""
        p.first_order_date = _day(p.first_order)
        p.last_order_date = _day(p.last_order)
        batch.append(p)
        if len(batch) >= 1000:
            _flush(CustomerProfile, batch)
            batch = []
    _flush(CustomerProfile, batch)


def _flush(CustomerProfile, batch):
    if batch:
        CustomerProfile.objects.bulk_update(
            batch, ["top_category", "brands_text", "first_order_date", "last_order_date"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerprofile_phone_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='brands_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_order_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_order_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='top_category',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        # Fill the new columns for rows imported before they existed. ``items`` stays NULL (unknown)
        # until the next import reads TotalUnits. Reverse is a no-op: the columns are dropped.
        migrations.RunPython(backfill_list_columns, migrations.RunPython.noop),
    ]
