# Generated by Django 5.2.17 on 2026-10-09 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customerprofile_list_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budtender_customer_id', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('covers_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='budtender_customer_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='budtender_link',
            field=models.CharField(blank=True, choices=[('', 'not linked'), ('phone', 'phone'), ('name_unique', 'unique exact name'), ('manual', 'manual')], db_default='', default='', max_length=16),
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('chat', 'Website chat'), ('call', 'Phone call')], max_length=8)),
                ('ref', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('message_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('kind', 'ref')},
            },
        ),
    ]
