from django.urls import path

from . import dashboards, views

urlpatterns = [
    path("", views.begin, name="begin"),
    path("pos/", views.screen, name="screen"),
    path("start/", views.start, name="start"),
    path("end/", views.end_session, name="end"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("scan/", views.scan, name="scan"),
    path("lookup/", views.lookup, name="lookup"),
    path("profile/", views.profile, name="profile"),
    path("customer/create/", views.create_customer, name="create_customer"),
    path("start/existing/", views.start_existing, name="start_existing"),
    path("customer/", views.customer, name="customer"),
    path("customer/full/", views.customer_full, name="customer_full"),
    path("menu/", views.menu, name="menu"),
    path("product/<product_id>/", views.product, name="product"),
    path("cart/add/", views.cart_add, name="cart_add"),
    path("cart/remove/", views.cart_remove, name="cart_remove"),
    path("cart/submit/", views.cart_submit, name="cart_submit"),
    path("phone-cart/claim/", views.phone_cart_claim, name="phone_cart_claim"),
    # roles + live queue
    path("door/", views.door, name="door"),
    path("door/scan/", views.door_scan, name="door_scan"),
    path("queue/", views.queue_panel, name="queue_panel"),
    path("queue/<int:visit_id>/claim/", views.claim, name="claim"),
    path("guest/", views.guest_start, name="guest_start"),
    path("shifts/", views.shifts, name="shifts"),
    path("shifts/<int:shift_id>/", views.shift_detail, name="shift_detail"),
    path("sessions/", views.sessions, name="sessions"),
    path("sessions/active/", views.sessions_active, name="sessions_active"),
    path("sessions/rollups/", views.sessions_rollups, name="sessions_rollups"),
    path("sessions/<int:visit_id>/", views.session_detail, name="session_detail"),
    path("sessions/<int:visit_id>/close/", views.session_close, name="session_close"),
    path("sessions/<int:visit_id>/delete/", views.session_delete, name="session_delete"),
    # Insights — manager BI (is_staff) + budtender self-service
    path("insights/", dashboards.overview, name="insights_overview"),
    path("insights/products/", dashboards.products, name="insights_products"),
    path("insights/customers/", dashboards.customers, name="insights_customers"),
    path("insights/budtenders/", dashboards.budtenders, name="insights_budtenders"),
    path("me/", dashboards.my_stats, name="my_stats"),
]
