# Generated by Django 5.2.15 on 2026-06-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=128)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('location_slug', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('slots', models.JSONField(blank=True, default=dict)),
                ('stage', models.CharField(default='WELCOME', max_length=24)),
                ('channel', models.CharField(default='chat', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('brand_affinity', models.JSONField(blank=True, default=dict)),
                ('category_affinity', models.JSONField(blank=True, default=dict)),
                ('strain_type_affinity', models.JSONField(blank=True, default=dict)),
                ('flavor_affinity', models.JSONField(blank=True, default=dict)),
                ('terpene_affinity', models.JSONField(blank=True, default=dict)),
                ('subcategory_affinity', models.JSONField(blank=True, default=dict)),
                ('thc_min', models.FloatField(blank=True, null=True)),
                ('thc_max', models.FloatField(blank=True, null=True)),
                ('price_tier', models.CharField(blank=True, max_length=8)),
                ('novelty_score', models.FloatField(default=0)),
                ('bucket_mix', models.JSONField(blank=True, default=dict)),
                ('purchase_history', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_slug', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(default='chat', max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('resolved', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_slug', models.CharField(choices=[('yakima', 'Yakima'), ('mount-vernon', 'Mount Vernon'), ('pullman', 'Pullman')], db_index=True, max_length=32, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_slug', models.CharField(blank=True, db_index=True, max_length=32)),
                ('channel', models.CharField(default='chat', max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', '-ts'], name='budtender_a_event_t_ecf078_idx'), models.Index(fields=['location_slug', '-ts'], name='budtender_a_locatio_ff183f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('content', models.TextField(blank=True)),
                ('chips', models.JSONField(blank=True, default=list)),
                ('result_skus', models.JSONField(blank=True, default=list)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='budtender.chatsession')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='budtender.customerprofile'),
        ),
        migrations.CreateModel(
            name='ManualPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_slug', models.CharField(db_index=True, max_length=32)),
                ('anchor_sku', models.CharField(db_index=True, max_length=64)),
                ('pair_sku', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('location_slug', 'anchor_sku', 'pair_sku')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_slug', models.CharField(choices=[('yakima', 'Yakima'), ('mount-vernon', 'Mount Vernon'), ('pullman', 'Pullman')], db_index=True, max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('strain', models.CharField(blank=True, max_length=128)),
                ('strain_type', models.CharField(blank=True, max_length=16)),
                ('thc_percent', models.FloatField(blank=True, null=True)),
                ('dominant_terpene', models.CharField(blank=True, max_length=64)),
                ('effects', models.JSONField(blank=True, default=list)),
                ('flavors', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_was', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('unit_weight', models.FloatField(blank=True, null=True)),
                ('potency_mg', models.FloatField(blank=True, null=True)),
                ('subcategory', models.CharField(blank=True, db_index=True, max_length=16)),
                ('margin_pct', models.FloatField(default=0)),
                ('velocity', models.FloatField(default=0)),
                ('margin_z', models.FloatField(default=0)),
                ('price_z', models.FloatField(default=0)),
                ('bucket', models.CharField(choices=[('core', 'Core'), ('traffic', 'Traffic driver'), ('profit', 'Profit driver')], db_index=True, default='core', max_length=8)),
                ('bucket_source', models.CharField(default='auto', max_length=8)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location_slug', 'category', 'availability'], name='budtender_p_locatio_eb613c_idx')],
                'unique_together': {('location_slug', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='SuggestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_slug', models.CharField(max_length=32)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('primary', 'primary'), ('pairing', 'pairing')], default='primary', max_length=12)),
                ('source', models.CharField(choices=[('chat', 'chat'), ('questionnaire', 'questionnaire'), ('catalog', 'catalog'), ('menu', 'menu')], default='chat', max_length=16)),
                ('paired_with_sku', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=32)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='budtender.customerprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='budtender.chatsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['phone', '-last_active_at'], name='budtender_c_phone_ab4ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedproduct',
            index=models.Index(fields=['customer', '-shown_at'], name='budtender_s_custome_b61ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedproduct',
            index=models.Index(fields=['session', '-shown_at'], name='budtender_s_session_553404_idx'),
        ),
    ]
