# Generated by Django 5.2.15 on 2026-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='syncstate',
            name='last_tx_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
