# Generated by Django 5.2.15 on 2026-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0002_customerprofile_name_syncstate_last_tx_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncstate',
            name='last_tx_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
