# Generated by Django 5.2.15 on 2026-07-09 19:59

import budtender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0003_syncstate_last_tx_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCartDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_token', models.CharField(db_index=True, default=budtender.models._phone_cart_token, max_length=64, unique=True)),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=80)),
                ('location_slug', models.CharField(choices=[('yakima', 'Yakima'), ('mount-vernon', 'Mount Vernon'), ('pullman', 'Pullman')], db_index=True, max_length=32)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_last4', models.CharField(blank=True, max_length=4)),
                ('pickup_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('released', 'Released'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('quote', models.JSONField(blank=True, default=dict)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['location_slug', 'status', '-updated_at'], name='budtender_p_locatio_efdbbf_idx'), models.Index(fields=['phone_hash', 'status', '-updated_at'], name='budtender_p_phone_h_d09c35_idx')],
            },
        ),
    ]
