# Generated by Django 5.2.15 on 2026-07-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0004_phonecartdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='primary_intent',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
