# Generated by Django 5.2.15 on 2026-08-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0005_chatsession_primary_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecartdraft',
            name='bundle_slug',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='phonecartdraft',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='phonecartdraft',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='phonecartdraft',
            name='source',
            field=models.CharField(choices=[('voice', 'Phone call'), ('online', 'Online order')], db_index=True, default='voice', max_length=16),
        ),
    ]
