# Generated by Django 5.2.15 on 2026-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0006_phonecartdraft_bundle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecartdraft',
            name='customer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='phonecartdraft',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('matched', 'Matched existing account'), ('new', 'No account — create at claim'), ('unresolved', 'Lookup unavailable')], max_length=16),
        ),
        migrations.AddField(
            model_name='phonecartdraft',
            name='dutchie_acct_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
