# Generated by Django 5.2.17 on 2026-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0009_batchlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('none', 'none')], max_length=8)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
