# Generated by Django 5.2.17 on 2026-10-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budtender', '0010_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='identity_via',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='dutchie_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='budtender.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='source',
            field=models.CharField(default='dutchie', max_length=16),
        ),
    ]
