# Generated by Django 5.2.17 on 2026-10-08 15:03

from django.db import migrations, models
from django.db.models.fields.json import KeyTextTransform
from django.db.models.functions import Substr


def backfill_visitor_id(apps, schema_editor):
    """Lift props.visitor_id into the new column for the history already stored (one UPDATE)."""
    Event = apps.get_model("budtender", "AnalyticsEvent")
    Event.objects.filter(visitor_id="", props__visitor_id__isnull=False).update(
        visitor_id=Substr(KeyTextTransform("visitor_id", "props"), 1, 64)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("budtender", "0011_customer_identity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["ts", "id"]},
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="visitor_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill_visitor_id, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session_token", "ts"], name="analyticsevent_session_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "ts"], name="chatmessage_session_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["-last_active_at"], name="chatsession_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["location_slug", "-started_at"], name="chatsession_store_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedproduct",
            index=models.Index(
                fields=["kind", "-shown_at"], name="suggested_kind_shown_idx"
            ),
        ),
    ]
