# Generated by Django 5.2.17 on 2026-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budtender", "0012_durability_indexes_visitor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="learned",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="memory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="memory_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
