# Generated by Django 5.2.17 on 2026-10-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budtender", "0013_customer_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("bought_exact", "bought_exact"),
                            ("bought_sibling", "bought_sibling"),
                            ("not_bought", "not_bought"),
                            ("unattributable", "unattributable"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "match_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "exact"),
                            ("sibling_size", "sibling_size"),
                            ("sibling_strain", "sibling_strain"),
                            ("sibling_both", "sibling_both"),
                            ("", ""),
                        ],
                        max_length=16,
                    ),
                ),
                ("matched_sku", models.CharField(blank=True, max_length=64)),
                ("matched_product_id", models.CharField(blank=True, max_length=64)),
                ("matched_name", models.CharField(blank=True, max_length=255)),
                (
                    "matched_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("matched_line", models.CharField(blank=True, max_length=160)),
                ("window_ends_at", models.DateTimeField(db_index=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="suggestedproduct",
            name="channel",
            field=models.CharField(db_index=True, default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="suggestedproduct",
            name="identity_via",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="suggestedproduct",
            name="sibling_key",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="suggestedproduct",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="suggestedproduct",
            index=models.Index(fields=["-shown_at"], name="suggested_shown_idx"),
        ),
        migrations.AddIndex(
            model_name="suggestedproduct",
            index=models.Index(
                fields=["channel", "-shown_at"], name="suggested_channel_shown_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedproduct",
            index=models.Index(
                fields=["location_slug", "-shown_at"], name="suggested_store_shown_idx"
            ),
        ),
        migrations.AddField(
            model_name="suggestionoutcome",
            name="suggestion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcome",
                to="budtender.suggestedproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestionoutcome",
            index=models.Index(
                fields=["status", "window_ends_at"], name="outcome_status_window_idx"
            ),
        ),
    ]
